version: 2
formats: all
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
    - requirements: docs/requirements.txt
    - path: .
