name: Release Python distribution

on:
  workflow_run:
      workflows: [Run tests]
      types:
        - completed

permissions:
  pages: write
  id-token: write

jobs:
  pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    if: ${{ startsWith(github.ref, 'refs/tags/') && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/colander-data-converter
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.16"
          python-version: "3.13"
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
